### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by liandrinha12** [victor-mrm/projetobd#2]
houve um problema!!!
![capturar](https://user-images.githubusercontent.com/32107896/31457150-4b12c396-ae92-11e7-9026-ee15cbcb235c.PNG)

**Comment by liandrinha12** [comment]
![od](https://user-images.githubusercontent.com/32107896/31457292-bcd0f25a-ae92-11e7-9aa0-f10e2bc99d1d.PNG)

**Comment by liandrinha12** [comment]
?
![sd](https://user-images.githubusercontent.com/32107896/31457355-e1ca4912-ae92-11e7-8641-57236766bf34.PNG)

**Comment by bmarchete** [comment]
Porque ainda não foi respondida esta questão ? @victor-mrm
